# Generated by Django 2.1.7 on 2019-09-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20190924_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqreport',
            name='result',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mcqreport',
            name='total_blank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcqreport',
            name='total_correct',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcqreport',
            name='total_wrong',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
