# Generated by Django 2.1.7 on 2019-09-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
