# Generated by Django 2.1.7 on 2019-11-19 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
