# Generated by Django 2.1.7 on 2019-11-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_article_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
