# Generated by Django 2.1.7 on 2019-11-06 17:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draft', '0003_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('label', models.CharField(default='', max_length=50)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pointer',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('self_loc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='self_loc', serialize=False, to='draft.Pointer')),
                ('root_loc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_loc', to='draft.Pointer')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.Directory'),
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together={('self_loc', 'root_loc')},
        ),
    ]
