# Generated by Django 2.1.7 on 2019-09-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqissue',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
