# Generated by Django 2.1.7 on 2019-10-30 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbox',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
